# Generated by Django 2.0.3 on 2018-03-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
