# Generated by Django 2.0.3 on 2018-03-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0003_crmuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='CrmUser',
        ),
    ]
