# Generated by Django 2.0.3 on 2018-04-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0004_auto_20180329_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
    ]
